import { FaUsers } from "react-icons/fa6";
import { BsCurrencyRupee } from "react-icons/bs";
import { FiAlertTriangle } from "react-icons/fi";
import { IoShieldCheckmarkOutline } from "react-icons/io5";

export const sites = [
  {
    id: 1,
    title: "Metor Corridor Line 3 (Tower B)",
  },
  {
    id: 2,
    title: "Greenfield Heights Phase II",
  },
  {
    id: 3,
    title: "NH-48 Flyover Widening Project",
  },
];

export const pagesLink = [
  {
    id: 1,
    title: "Dashboard Overview",
    icon: "📊",
    route: "dashboard",
  },
  {
    id: 2,
    title: "Mark Attendance",
    icon: "📅",
    route: "mark-attendence",
  },
  {
    id: 3,
    title: "Labour Directory",
    icon: "👷‍♂️",
    route: "labour-directory",
  },
  {
    id: 4,
    title: "Wage Calculator",
    icon: "💰",
    route: "wage-calculator",
  },
  {
    id: 5,
    title: "Payment & Dues Ledger ",
    icon: "🧾",
    route: "payment-leadger",
  },
];

export const wageCalculation = [
  {
    id: 1,
    title: "Present on Site Today",
    calc: "18 / 20",
    desc: "Workers present today (out of 20 total)",
    opt: "90% Site Headcount Turnout",
    icon: <FaUsers />,
    valueCol: "text-black-700",
    commentCol: "text-green-700",
    colIcon: "text-green-400",
    colBg: "bg-green-50",
    textCal: "text-green-900",
  },
  {
    id: 2,
    title: "Today's Wage Accrual",
    calc: "₹12,960",
    desc: "Avg ₹720/worker (Base + 4h OT)",
    opt: "Total wages payable today",
    icon: <BsCurrencyRupee />,
    valueCol: "text-black-400",
    commentCol: "text-slate-500",
    colIcon: "text-orange-400",
    colBg: "bg-orange-50",
    textCal: "text-orange-900",
  },
  {
    id: 3,
    title: "Total Pending Dues",
    calc: "₹48,600",
    desc: "Outstanding Payments",
    opt: "Payout Cycle: Saturday",
    icon: <FiAlertTriangle />,
    valueCol: "text-red-700",
    commentCol: "text-orange-400",
    colIcon: "text-red-600",
    colBg: "bg-red-50",
    textCal: "text-red-900",
    payNow: "Pay Now",
    navlink: "payment",
  },
  {
    id: 4,
    title: "Disbursed This Month",
    calc: "₹2,84,400",
    desc: "Payment made this month",
    opt: "96.4% compliance clearance",
    icon: <IoShieldCheckmarkOutline />,
    valueCol: "text-green-700",
    commentCol: "text-gray-600",
    colIcon: "text-blue-400",
    colBg: "bg-blue-50",
    textCal: "text-blue-900",
  },
];

export const attendencePunch = [
  {
    id: 1,
    labourer: "Ramesh Kumar",
    laburId: "SHR-101",
    category: "Skilled Mason",
    dailyWage: "850",
    status: "Absent (A)",
  },
  {
    id: 2,
    labourer: "Sunita Devi",
    laburId: "SHR-102",
    category: "Helper / Labour",
    dailyWage: "580",
    status: "Present (P)",
  },
  {
    id: 3,
    labourer: "Mohammad Arif",
    laburId: "SHR-103",
    category: "Barbender",
    dailyWage: "800",
    status: "Present (P)",
  },
  {
    id: 4,
    labourer: "Rajesh Sardar",
    laburId: "SHR-104",
    category: "Electrician",
    dailyWage: "900",
    status: "Present (P)",
  },
  {
    id: 5,
    labourer: "Lakhpat Singh",
    laburId: "SHR-105",
    category: "Skilled Mason",
    dailyWage: "850",
    status: "Present (P)",
  },
  {
    id: 6,
    labourer: "Lakshmi Bai",
    laburId: "SHR-106",
    category: "Helper / Labour",
    dailyWage: "580",
    status: "Present (P)",
  },
];

export const tradeRoleData = [
  {
    id: 1,
    tradeRole: "Skilled Mason",
    wage: "850",
  },
  {
    id: 2,
    tradeRole: "Electrician",
    wage: "900",
  },
  {
    id: 3,
    tradeRole: "Carpentar",
    wage: "820",
  },
  {
    id: 4,
    tradeRole: "Barbender",
    wage: "850",
  },
  {
    id: 5,
    tradeRole: "Plumber",
    wage: "850",
  },
  {
    id: 6,
    tradeRole: "Helper / Labour",
    wage: "580",
  },
];

export const OtMoney = [
  { id: 1, role: "Skilled Mason", money: "106" },
  { id: 2, role: "Helper / Labour", money: "73" },
  { id: 3, role: "Barbender", money: "100" },
  { id: 4, role: "Electrician", money: "113" },
  { id: 5, role: "Carpentar", money: "103" },
  { id: 6, role: "Plumber", money: "106" },
];

export const siteDashboardData = {
  1: {
    wageCalculation: [
      {
        id: 1,
        title: "Present on Site Today",
        calc: "18 / 20",
        desc: "Workers present today (out of 20 total)",
        opt: "90% Site Headcount Turnout",
        icon: <FaUsers />,
        valueCol: "text-black-700",
        commentCol: "text-green-700",
        colIcon: "text-green-400",
        colBg: "bg-green-50",
        textCal: "text-green-900",
      },
      {
        id: 2,
        title: "Today's Wage Accrual",
        calc: "₹12,960",
        desc: "Avg ₹720/worker (Base + 4h OT)",
        opt: "Total wages payable today",
        icon: <BsCurrencyRupee />,
        valueCol: "text-black-400",
        commentCol: "text-slate-500",
        colIcon: "text-orange-400",
        colBg: "bg-orange-50",
        textCal: "text-orange-900",
      },
      {
        id: 3,
        title: "Total Pending Dues",
        calc: "₹48,600",
        desc: "Outstanding Payments",
        opt: "Payout Cycle: Saturday",
        icon: <FiAlertTriangle />,
        valueCol: "text-red-700",
        commentCol: "text-orange-400",
        colIcon: "text-red-600",
        colBg: "bg-red-50",
        textCal: "text-red-900",
        payNow: "Pay Now",
        navlink: "payment",
      },
      {
        id: 4,
        title: "Disbursed This Month",
        calc: "₹2,84,400",
        desc: "Payment made this month",
        opt: "96.4% compliance clearance",
        icon: <IoShieldCheckmarkOutline />,
        valueCol: "text-green-700",
        commentCol: "text-gray-600",
        colIcon: "text-blue-400",
        colBg: "bg-blue-50",
        textCal: "text-blue-900",
      },
    ],

    attendencePunch: [
      {
        id: 1,
        labourer: "Ramesh Kumar",
        laburId: "SHR-101",
        category: "Skilled Mason",
        dailyWage: "850",
        status: "Absent (A)",
        mobileNo: "9876543210",
        aadharNo: "914796166204",
        daysWork:"5.5",
        cashAdvanced:"500",
        ot: "0",
      },
      {
        id: 2,
        labourer: "Sunita Devi",
        laburId: "SHR-102",
        category: "Helper / Labour",
        dailyWage: "580",
        status: "Present (P)",
        mobileNo: "9876543210",
        aadharNo: "914796166204",
        daysWork:"6.5",
        cashAdvanced:"200",
        ot: "0",
      },
      {
        id: 3,
        labourer: "Mohammad Arif",
        laburId: "SHR-103",
        category: "Barbender",
        dailyWage: "800",
        status: "Present (P)",
        mobileNo: "9876543210",
        aadharNo: "914796166204",
        daysWork:"7.5",
        cashAdvanced:"0",
        ot: "0",
      },
      {
        id: 4,
        labourer: "Rajesh Sardar",
        laburId: "SHR-104",
        category: "Electrician",
        dailyWage: "900",
        status: "Present (P)",
        mobileNo: "9876543210",
        aadharNo: "914796166204",
        daysWork:"6.5",
        cashAdvanced:"0",
        ot: "0",
      },
      {
        id: 5,
        labourer: "Lakhpat Singh",
        laburId: "SHR-105",
        category: "Skilled Mason",
        dailyWage: "850",
        status: "Present (P)",
        mobileNo: "9876543210",
        aadharNo: "914796166204",
        daysWork:"6.5",
        cashAdvanced:"1000",
        ot: "0",
      },
      {
        id: 6,
        labourer: "Lakshmi Bai",
        laburId: "SHR-106",
        category: "Helper / Labour",
        dailyWage: "580",
        status: "Present (P)",
        mobileNo: "9876543210",
        aadharNo: "914796166204",
        daysWork:"6.5",
        cashAdvanced:"0",
        ot: "0",
      },
    ],
  },
  2: null,
  3: null,
};
