export const workerCard = [
  {
    id: 1,
    title: "Attendance",
    logo: "📅",
    main: "7.5 Days",
    desc: "7 full days + 1 half day",
    type: "Current Month",
    autoText: "Sep 2026",
    mainBG: "white",
    titleBG: "slate",
    logoBG: "emerald-100",
    logoText: "emerald",
    mainFont: "black",
    mainText: "slate",
    descText: "emerald",
    typeBorder: "slate",
    autoTextCol: "slate",
    mainCol: "slate-200",
  },
  {
    id: 2,
    title: "Overtime",
    logo: "⏱️",
    main: "2.0 Hours",
    desc: "+₹213 extra earning",
    type: "Rate: 1.0x Regular",
    autoText: "Calculated",
    mainBG: "white",
    titleBG: "slate",
    logoBG: "blue-300",
    logoText: "blue",
    mainFont: "black",
    mainText: "blue",
    descText: "blue",
    typeBorder: "slate",
    autoTextCol: "blue",
    mainCol: "slate-200",
  },
  {
    id: 3,
    title: "Total Earned",
    logo: "💰",
    main: "₹6,588",
    desc: "Basic Salary + Overtime",
    type: "Advances deducted",
    autoText: "-₹500",
    mainBG: "white",
    titleBG: "slate",
    logoBG: "amber-200",
    logoText: "orange",
    mainFont: "black",
    mainText: "slate",
    descText: "slate",
    typeBorder: "slate",
    autoTextCol: "red",
    mainCol: "slate-200",
  },
  {
    id: 4,
    title: "Net Balance Due ",
    logo: "💵",
    main: "₹3,088",
    desc: "Payment Cycle: Every Saturday",
    type: "Paid: ₹3,000",
    autoText: "View slip →",
    mainBG: "amber-50",
    titleBG: "slate",
    logoBG: "amber-200",
    logoText: "amber",
    mainFont: "black",
    mainText: "red",
    descText: "red",
    typeBorder: "amber",
    autoTextCol: "red",
    mainCol: "amber-300",
  },
];

export const navlinkItem = [
  {
    id: 1,
    title: "Attendance Log ",
    icon: "📅",
    route: "attendence-log",
  },
  {
    id: 2,
    title: "Wage Slip ",
    icon: "🧾",
    route: "wage-slip",
  },
  {
    id: 3,
    title: "Payment Receipts ",
    icon: "💳",
    route: "payment-receipt",
  },
  {
    id: 4,
    title: "Report Issue ",
    icon: "⚠️",
    route: "report-issue",
  },
];

export const issueCategoryHed = [
  { id: 1, title: "Attendence mark absent while I was present" },
  { id: 2, title: "Overtime extra hours not credited" },
  { id: 3, title: "Cash Payment received as less than due" },
  { id: 4, title: "Advanced was deducted twice" },
  { id: 5, title: "Drinking water and safety equipement missing" },
];
