export const workerCard = [
  {
    id: 1,
    title: "Attendance",
    logo: "📅",
    main: "7.5 Days",
    desc: "7 पूरे दिन + 1 आधा दिन",
    type: "Current Month",
    autoText: "Sep 2026",
    mainBG: "",
    titleBG: "",
    logoBG: "",
    logoText: "",
    mainFont: "",
    mainText: "",
    descText: "",
    typeBorder: "",
    autoTextCol: "",
  },
  {
    id: 2,
    title: "Overtime",
    logo: "⏱️",
    main: "2.0 Hours",
    desc: "+₹213 extra earning",
    type: "Rate: 1.0x Regular",
    autoText: "Calculated",
    mainBG: "",
    titleBG: "",
    logoBG: "",
    logoText: "",
    mainFont: "",
    mainText: "",
    descText: "",
    typeBorder: "",
    autoTextCol: "",
  },
  {
    id: 3,
    title: "Total Earned",
    logo: "💰",
    main: "₹6,588",
    desc: "Basic Salary + Overtime",
    type: "Advances deducted",
    autoText: "-₹500",
    mainBG: "",
    titleBG: "",
    logoBG: "",
    logoText: "",
    mainFont: "",
    mainText: "",
    descText: "",
    typeBorder: "",
    autoTextCol: "",
  },
  {
    id: 4,
    title: "Net Balance Due ",
    logo: "💵",
    main: "₹3,088",
    desc: "Payment Cycle: Every Saturday",
    type: "Paid: ₹3,000",
    autoText: "View slip →",
    mainBG: "",
    titleBG: "",
    logoBG: "",
    logoText: "",
    mainFont: "",
    mainText: "",
    descText: "",
    typeBorder: "",
    autoTextCol: "",
  },
];
